### ISSUE TITLE
Compile errors

### ISSUE THREAD

**Issue by bpenwell** [casper-ecosystem/kv-storage-contract#10]
Following the command "make test" as stated on the repo, I tried building it; however, I ran into a build error while building the tests. See them below

image

Errors:
tests/src/lib.rs:133:9 "move occurs because value1 has type casper_types::PublicKey, which does not implement the Copy trait" | "value borrowed here after move"
tests/src/lib.rs:134:9 "move occurs because value2 has type casper_types::PublicKey, which does not implement the Copy trait" | "value borrowed here after move"
tests/src/kv_storage.rs:25:27 "move occurs because account has type casper_types::PublicKey, which does not implement the Copy trait" | "value borrowed here after move"

**Comment by bpenwell** [comment]
I'm unable to figure out how to setup a pull request for this issue, so I'm putting my solution down, should it be the best solution.

This is the code I edited and compiled successfully for me.
lib.rs:132: 
![image](https://user-images.githubusercontent.com/18432993/121604387-4962fe80-c9ff-11eb-956f-b5b4f4fbe02e.png)

kv_storage.rs: 18-40
![image](https://user-images.githubusercontent.com/18432993/121604373-3e0fd300-c9ff-11eb-9e6f-680285d26104.png)

**Comment by deuszex** [comment]
Thanks, sorry about the late reply. This was because of a change in traits that were implemented on the cryptographic types.
