### ISSUE TITLE
Build is broken & sample needs updating

### ISSUE THREAD

**Issue by sfeast** [casper-ecosystem/kv-storage-contract#13]
When running `make build-contract`:

```
error: failed to download `uint v0.9.3`

Caused by:
  unable to get packages from source

Caused by:
  failed to parse manifest at `/Users/steve/.cargo/registry/src/github.com-1ecc6299db9ec823/uint-0.9.3/Cargo.toml`

Caused by:
  feature `edition2021` is required

  consider adding `cargo-features = ["edition2021"]` to the manifest
make: *** [build-contract] Error 101
```

Also the contract requires some updating to latest APIs

**Comment by euanmcf-cl** [comment]
Issue fixed.

Sample needed updating.

**Comment by sfeast** [comment]
@euanmcf-cl I haven't re-tested but I don't see how anything could have been fixed since no new code has been committed 🧐   Perhaps something wrong with my setup but pretty sure not since I saw others say they had a problem with  this sample as well.
